### ISSUE TITLE
Ads not shown on rerender

### ISSUE THREAD

**Issue by friendOfOurs** [coop182/jquery.dfp.js#103]
I use Marionette for rendering views.
On the first render of the page where the ads are shown the $.dfp({...}) is called. On every subsequent google console shows there is the ad and it is fetched properly, but nothing is being displayed. 
If I call $.dfp({...}) on **every** render the ads are being displayed but the console shows an error:
"googletag.defineSlot was called without a matching googletag.display call"
The console also says there are 2 ad slots altough there is only one that is actually being re-rendered.
I tought refreshExisting would solve the problem, but it didn't.
So, I was thinking maybe the best workaround would be to call $.dfp on every render, but to somehow delete/remove $.dfp when the page is being destroyed...
Any ideas or tips how to effectively solve this issue are more than welcome.
Thanks in advance!

**Comment by inspire22** [comment]
It's not a full answer, but sounds like you're using ajax or something for changing pages, so the full browser screen doesn't refresh, right?

Ruby on rails does something similar, here's the code they use to fix it - you might be able to adapt it http://reed.github.io/turbolinks-compatibility/doubleclick_for_publishers.html

**Comment by vonec** [comment]
var pubadsService = googletag.pubads();
                pubadsService.pubads().clear();

this should fix the issue ajax pages reloading content

**Comment by vonec** [comment]
`        createAds = function (dfpOptions, $adCollection) {
            var googletag = window.googletag;


            googletag.cmd.push(function() {
              return googletag.destroySlots();
            });
            `
