### ISSUE TITLE
dfpID should not be mandatory

### ISSUE THREAD

**Issue by HeadOnAPlate** [coop182/jquery.dfp.js#108]
We pass the complete ad unit from the back-end to our front-end rendering.
So this already includes the network code (dfpID).
This is necessary as we decide against which dfp network we run depending on some back-end configuration.
As such we would like to leave the dfpID empty.
At the moment this breaks the requests, because of https://github.com/coop182/jquery.dfp.js/blob/master/jquery.dfp.js#L164 and https://github.com/coop182/jquery.dfp.js/blob/master/jquery.dfp.js#L166.

Could the parameter be checked on empty and if so, leave out the '/'?

**Comment by coop182** [comment]
This seems like a pretty good idea... I will code it up when I get a bit of spare time soon :smile:

**Comment by coop182** [comment]
Just released a new version that should let you do this... I'm going to close this now in anticipation of everything working perfectly haha... please feel free to reopen it if there is anything not working.

**Comment by HeadOnAPlate** [comment]
Thanks for a fast fix. I'll test it out on monday.
