### ISSUE TITLE
DFP ads timeout in chrome

### ISSUE THREAD

**Issue by Manibala** [coop182/jquery.dfp.js#115]
While testing found that ads are timing out if session sits for a while, and don't come back upon hard refresh, we shouldn't have to clear cache for something like this, the ads should render each time we refresh.

**Comment by coop182** [comment]
I'm not sure what you mean by timing out?

The ads all seem to be loading fine for me... are you refreshing them with a timer or something?

Also you seem to be using an old version of my script... you could try the latest version.

My script is only a wrapper around DFP so if the ads are loading then everything is generally fine and most problems after the ads have loaded will be with DFP itself.
