### ISSUE TITLE
c.defineSlot is not a function

### ISSUE THREAD

**Issue by gvanderest** [coop182/jquery.dfp.js#116]
We are going to try upgrading to the latest version (2.4.1) from our current (2.0.0) but just wanted to make sure that this is noted, as it might still be an issue:

TypeError: c.defineSlot is not a function. (In 'c.defineSlot("/"+f+"/"+d,h,e)', 'c.defineSlot' is undefined)

Primarily affecting Safari users on iOS.

**Comment by coop182** [comment]
That code has been changed in newer versions... so it might be fine now...
