### ISSUE TITLE
Ad creative not changing

### ISSUE THREAD

**Issue by ilikourou** [coop182/jquery.dfp.js#118]
Hello.

First of all, great plugin.

I am having the following issue:

I am using jquery-pjax (https://github.com/defunkt/jquery-pjax) in my website. Everything seems to be working fine, including jquery.dfp, except from the fact that ad creatives do not change on subsequent page loads using pjax. This means that if AdCreative1 is displayed on Page1, no matter how many times I come back to Page1, the same creative  (AdCreative1) will be displayed.

If I refresh the page through the browser, a new creative is fetched, as normal.

I have tried using the provided callbacks, along with some other possible solutions (such as window.googletag.pubads().clear() and window.googletag.pubads().refresh(), before and after each ajax page load respectively), but neither seems to be working as expected.

Any help?

Thanks,
Ilias

**Comment by ilikourou** [comment]
Edit: When using ```data-adunit``` instead of ```id```, each ad (creative) is displayed once and then nothing appears on the ad slot.

For example, assuming I have 3 banners (creatives) for a specific ad slot, first page load displays Banner1, second page load displays Banner2 and third page load displays Banner3. Then, on the fourth page load, nothing is displayed. All these slots are in the same page and this page is loaded through jquery-pjax.

**Comment by coop182** [comment]
Do you have an example page that I could view?

**Comment by ilikourou** [comment]
i ended up doing it like so in every page load:

    if (window.googletag && googletag.apiReady) {
        window.googletag.pubads().updateCorrelator();
    }
    $.dfp({
        dfpID: '4205444',
        collapseEmptyDivs: true
    });

Without `window.googletag.pubads().updateCorrelator()` the ad slot did not reload (get filled) on each page.
However, the problem I just discovered right now, is that line item's impressions count in DFP is not correct. I know that a line item has delivered way more than 200.000 impressions, but in DFP I can see that only 56.000 impressions are measured. Any idea why this is happening?

The site I am using jquery dfp is www.rocking.gr

Thanks,
Ilias
