### ISSUE TITLE
Wrong impressions count

### ISSUE THREAD

**Issue by ilikourou** [coop182/jquery.dfp.js#123]
Hello.

My code looks like this:

    if (window.googletag && googletag.apiReady) {
        window.googletag.pubads().updateCorrelator();
    }
    $.dfp({
        dfpID: 'XXXXXX',
        collapseEmptyDivs: true
    });

Without `window.googletag.pubads().updateCorrelator()` the ad slot did not reload (get filled) on each page.
However, the problem I just discovered right now, is that line item's impressions count in DFP is not correct. I know that a line item has delivered way more than 200.000 impressions, but in DFP I can see that only 56.000 impressions are measured. Any idea why this is happening? Does it have to do with `updateCorrelator()`?

The site I am using jquery dfp is www.rocking.gr

Thanks,
Ilias

**Comment by coop182** [comment]
I'm not familiar with the updateCorrelator function sorry, I haven't used it before.

Could you try running that after all the ads have loaded? Perhaps with the afterAllAdsLoaded callback?
