### ISSUE TITLE
First Ad Unit Size Not Taking Precedence

### ISSUE THREAD

**Issue by coleh33** [coop182/jquery.dfp.js#145]
I  have created a size mapping for a DFP Position and it appears to be pulling from both sizes even though I have specified one size to be first priority.

`{ browser: [728, 90], ad_sizes: [[300,600],[300, 250]] },`

I would like the 300x600 to always pull if one is available, however the 300x250 also shows up in rotation with the 300x600.  The way I understood it was that the 300x600 should always have first priority if defined first.

**Comment by soreng** [comment]
That is not how it works. You are just "selecting" ads. 

If it was SQL, it would be "SELECT * FROM Creatives WHERE Size IN ('300x600','300x250') ORDER BY (something google)".

Google takes care of sorting, so the campaigns that need the impression most gets it.

You can only affect the "WHERE", so to prioritize one size, you would need to make multiple requests (which you shouldn't).

**Comment by coleh33** [comment]
Thanks for the clarification.
