### ISSUE TITLE
Ad disappears on ajax call. 

### ISSUE THREAD

**Issue by not-original** [coop182/jquery.dfp.js#55]
First, thanks for a great script. 

Second, I can't seem to get dpf to work on a second ajax call.  It works the first time. 

For example:
http://wptschedule.org/GenreGroup/1012/Arts-Film-and-Music/?google_console=1

The ad loads.  But if you click any links on the left, which does an ajax call to refresh content on the right, the ad disappears. 

The DFP console only tells me that the ad did not fetch. 

What is strange is both the initial code, and subsequent clicks, load the same file. 

I have tried setting enableSingleRequest to false, and refresh existing to false, but neither seem to have any effect. 

There are some empty ad slots (used in the header throughout the site) that aren't being utilized.  But when I tested, I still had the same issue. 

My ajax call looks like this:

```
$.post(theurl, function(data) {     
    $('#results').html(data);   
$.dfp({
    dfpID:'1007345/wpt_banner',
    enableSingleRequest:false,
    refreshExisting:false,
    collapseEmptyDivs:true
});
```

...etc, etc

And on the results page I have
  <div class="adunit" data-adunit="div-gpt-ad-1387561917828-0" data-dimensions="728x90"></div>

Not sure why it only works the first load, and not second. 

  <div class="adunit" data-adunit="div-gpt-ad-1387561917828-0" data-dimensions="728x90"></div>

Any help at all appreciated.

**Comment by derekcoleman** [comment]
Has anyone been able to solve this or get ads refreshing every 30 seconds and working for ajax pages. I have the ads refreshing but it currently doesn't work once I change pages two or more times. This is what my code looks like right now. 

`$('.adunit:not(".display-none")').dfp({
            dfpID: '52137663',
			enableSingleRequest: false,
			afterAllAdsLoaded: function() {
			setInterval(function() {
            jQuery.dfp();
        }, '30000');
    }
        });`
