### ISSUE TITLE
synchronous rendering

### ISSUE THREAD

**Issue by hellfire6969** [coop182/jquery.dfp.js#66]
Hi there

Thank you for your great plugin, it is really handy and helpful. We would like to have mix asynchronous and synchronous tags on the same page, I am using your plugin to put the expandable banner on this page, http://www.tracksmag.com/banner.html, but it is not expandable.  It should looks like that http://www.tracksmag.com/expandable-banner.html, how can we do this instead of putting asynchronous tag in iframe? Thank you. Looking forwards to hearing from you. 

Best Regards

Robin

**Comment by lfbvyo** [comment]
@hellfire6969 how was the result ? I have the same problem.

**Comment by anxfeb** [comment]
hi @hellfire6969 how was the result ? I have the same problem too.
