### ISSUE TITLE
disableInitialLoad and manual display / refresh

### ISSUE THREAD

**Issue by falzhobel** [coop182/jquery.dfp.js#72]
Hi,

I'm trying to implement google dfp ads by first defining slots, and afterwards calling the display and refresh methods as shown in the Infinite contents example here (see  part):

https://support.google.com/dfp_premium/answer/4578089?hl=en&ref_topic=4390040

When I set `disableInitialLoad: true` in the $(selector).dfp(); initialization and then call the refresh method it doesn't work.

Any pointers on how I could "lazy-load" ads with your plugin? And also individually refresh ads instead of the whole unit?

Thanks for the great plugin by the way!

**Comment by pnmcosta** [comment]
Hi All,

This has worked great for me, requirement was for each ad to refresh separately and at different timeouts, so:

    $.dfp({
        dfpID: '123...',
        enableSingleRequest: false,
        afterEachAdLoaded: function (e) {
            var adUnit = $(e);
            var refreshTimeOut = adUnit.data('refresh');
            var adUnitData = adUnit.data('googleAdUnit');
            if (refreshTimeOut && adUnitData && adUnit.hasClass('display-block')) {
                console.log('setting timeout of ' + refreshTimeOut + ' to ' + adUnit.attr('id'));

                setTimeout(function () {
                    console.log('refreshing ' + adUnit.attr('id'));
                    window.googletag.pubads().refresh([adUnitData]);
                }, refreshTimeOut);
            }
        }
    });

Not a clean solution, it would probably be nice to see this implemented as recommended above $('#ad-1').dfp('refresh')

Thanks,
P.

**Comment by coop182** [comment]
You should be able to set `disableInitialLoad: true` and then when you want to refresh a specific ad unit you could do it outside of the script by doing the following:

```javascript
var adunit = $('#id').data('googleAdUnit');
window.googletag.pubads().refresh([adunit]);
```

If that doesn't work let me know... sorry for the huge delay with this answer!
