### ISSUE TITLE
Single Request for Roadblocks on Refresh()?

### ISSUE THREAD

**Issue by mickharper** [coop182/jquery.dfp.js#77]
I've run into what is perhaps a general DFP issue that you might know a workaround for. 

In order to have roadblocked ads, you need single request mode enabled. If you have slideshows though on your site and need to refresh all your ad slots -- subsequent calls frequently don't treat the new requests as a single (roadblocked) request and you end up with a mix of creatives from more than one line item.

Even when I include a new dfp() function when a user loads a new slide -- it still renders as a refresh of each of the units and doesn't appear to function as a full/single request to render a roadblock correctly (google_force_console tells me it is using single request mode here -- yet I still end up with a jumble of units). 

I'm wondering if there is another way to solve this -- or if perhaps DFP could be fully reinitialized -- almost as if the page were reloaded?

**Comment by derekcoleman** [comment]
@mickharper are you able to provide your script for this? I am having the same issue.
