### ISSUE TITLE
Problem with size mapping

### ISSUE THREAD

**Issue by pixelsucht** [coop182/jquery.dfp.js#83]
Hi,
i try to set up a responsive ad with size-mapping.
This is my setup in the page:

```
<div class="adunit" id="mobile_billboard" data-adunit="mobile_billboard" data-dimensions="800x250,800x200,800x150,728x90,600x50,600x100,600x150,320x150,320x100,320x50"></div>

        <script type="text/javascript"> 
            $('#mobile_billboard').dfp({
                dfpID:'10611xx',
                sizeMapping: { 
                        'mobile_billboard': [
                            {browser: [   0,   0], ad_sizes: [[320, 50], [320, 100], [320, 150]]},
                            {browser: [ 640, 480], ad_sizes: [[320, 50], [320, 100], [320, 150]]},
                            {browser: [ 980, 600], ad_sizes: [[600, 50], [600, 100], [600, 150]]},
                            {browser: [1024, 768], ad_sizes: [[800, 150], [800,200],[800,250], [728,90]]}
                        ],     
                    }          
                });            
        </script>

```

But on my testpage with browser > 1024x768 i get random ads of all sizes. (320x100) for example.
Am I doing something wrong?
I thought I should get only the "big" ads on big screens.

**Comment by e-kikar-net** [comment]
Please give example of using data-size-mapping

**Comment by vhugogarcia** [comment]
@rechengehirn could you please share a sample about how you solved it.

Thanks in advance

**Comment by e-kikar-net** [comment]
You can see it here: view-source:http://mame.kikar.co.il/

 targeting = {};
$(function() {$.dfp({  
        		sizeMapping: 
	{ 
		mappingTop: [
			{browser: [970, 400], ad_sizes: [970, 90] }, 
			{browser: [728, 300], ad_sizes: [728, 90] }, 
			{browser: [468, 300], ad_sizes: [468, 60] }, 
			{browser: [320, 200], ad_sizes: [320,100] }, 
			{browser: [1, 1], ad_sizes: [234, 60]}], 
	}, 
        		        		dfpID: 7103878,		
collapseEmptyDivs:'original',
	 	setTargeting:targeting    });});

**Comment by ozeone** [comment]
Solved this, here is a pen with the markup
https://codepen.io/martink/pen/zjLrbx

**Comment by maruf-cefalo** [comment]
@ozeone, I can not visit the codepen, do you still have it?

**Comment by maruf-cefalo** [comment]
> Found it out. I didn't realize that i have to set the data-size-mapping attribute in the div tag

HI, @rechengehirn, do you still have any example of data-size-mapping?

**Comment by EitanGiller** [comment]
<div class="adunit" *data-size-mapping*="*mappingTop*" data
-adunit="TopHomePage"></div>
<script>
$.dfp({
dfpID: "1234567", collapseEmptyDivs: !0, refreshAll: !1, *sizeMapping*:
{
*mappingTop*: [
{browser: [970, 400], ad_sizes: [970, 90] },
{browser: [728, 300], ad_sizes: [728, 90] },
{browser: [468, 300], ad_sizes: [468, 60] },
{browser: [320, 200], ad_sizes: [320,100] },
{browser: [1, 1], ad_sizes: [234, 60]}],
},
});
</script>
