### ISSUE TITLE
Missing comma in example-bootstrap.js

### ISSUE THREAD

**Issue by chaoming** [coop182/jquery.dfp.js#85]
// Callback which is run after the render of all ads.
afterAllAdsLoaded: function (adUnits) {
	// Do something after all ads are loaded.
}

Missing a comma and causing a syntax error, should be:

// Callback which is run after the render of all ads.
afterAllAdsLoaded: function (adUnits) {
	// Do something after all ads are loaded.
},

**Comment by coop182** [comment]
Thanks, I have fixed it now :smile:
