### ISSUE TITLE
collapseEmptyDivs parameters

### ISSUE THREAD

**Issue by ehoch** [coop182/jquery.dfp.js#86]
So GPT's collapseEmptyDivs takes 2 parameters (https://support.google.com/dfp_premium/answer/3072674?hl=en), but your library does not allow them to be passed in.

And ideally, I'd love to be able to do this on a unit. The idea being I'd like to have a unit that usually collapsed on by default on only appears / loads when there's an ad. (rare)

**Comment by willhaynes** [comment]
According to the documentation, `collapseEmptyDivs()` [takes one parameter](https://developers.google.com/doubleclick-gpt/reference#googletag.PubAdsService_collapseEmptyDivs), where `setCollapseEmptyDivs()` [takes two](https://developers.google.com/doubleclick-gpt/reference#googletag.Slot_setCollapseEmptyDiv).

I do not believe this library currently makes any call to `setCollapseEmptyDiv`, which is done on a per ad basis. What exactly is it you'd like to do?

**Comment by coop182** [comment]
I could look at implementing the per slot code - that might be handy. For now you can get the desired behaviour by using the CSS classes that my script adds to your adunits.

Depending exactly on what you want to do you can use a combination of the .adunit, .display-block and .display-none classes to do per slot or whole page collapsing... for example:

// Hide all adunits by default
.adunit {
    display: none;
}

// Show ad units which have an ad in them
.adunit.display-block {
    display: block;
}
