### ISSUE TITLE
How to define multiple ad slots?

### ISSUE THREAD

**Issue by memory-d** [coop182/jquery.dfp.js#88]
I'm a newbie on js. Please advise me.

**Comment by coop182** [comment]
Take a look at the source code of this page:

http://coop182.github.io/jquery.dfp.js/dfptests/1.html

**Comment by memory-d** [comment]
1.I used this pattern on my js file. Bcoz my dfpID is unique. How can I define multiple adslots if I used this pattern.
$('selector').dfp({
    dfpID:'xxxxxxxxx',
    sizeMapping: {
        'my-default': [
            {browser: [1024, 768], ad_sizes: [980, 185]},
            {browser: [ 980, 600], ad_sizes: [[728, 90], [640, 480]]}
            {browser: [   0,   0], ad_sizes: [88, 31]}
        ],
    }
});

2. About responsive ads on my html markup I already wrote data-dimensions="393x176,450x500" but look like it's doesn't working. What I am doing wrong?

**Comment by memory-d** [comment]
1.DONE. Thanks for your advised. :)
2.Still not working.
