### ISSUE TITLE
Using data-size-mapping parameter

### ISSUE THREAD

**Issue by e-kikar-net** [coop182/jquery.dfp.js#89]
Hi!
How to use data-size-mapping parameter?
Could you provide an example, please?
Thanks

**Comment by memory-d** [comment]
Maybe Try this : data-size-mapping="same as data-dimensions" data-dimensions="unit-value"

**Comment by e-kikar-net** [comment]
Thanks

**Comment by memory-d** [comment]
is it working?

**Comment by e-kikar-net** [comment]
I've found yesterday an example in internet and it works. Thanks

**Comment by memory-d** [comment]
Cool, Can you show me your markup? Boz Sometime my ads is not show the correct size.

**Comment by e-kikar-net** [comment]
You can view the source of mame.Co.il . Or I can answer you later..

**Comment by e-kikar-net** [comment]
<div class="adunit" *data-size-mapping*="*mappingTop*"
data-adunit="TopHomePage"></div>
<script>
$.dfp({
dfpID: "1234567", collapseEmptyDivs: !0, refreshAll: !1, *sizeMapping*:
{
*mappingTop*: [
{browser: [970, 400], ad_sizes: [970, 90] },
{browser: [728, 300], ad_sizes: [728, 90] },
{browser: [468, 300], ad_sizes: [468, 60] },
{browser: [320, 200], ad_sizes: [320,100] },
{browser: [1, 1], ad_sizes: [234, 60]}],
},
});
</script>

**Comment by mikkotikkanen** [comment]
This approach seems to work, however, it would be nice to have it explained in the documentation
