### ISSUE TITLE
Hard-Code GPT tags alongside jQuery DFP

### ISSUE THREAD

**Issue by ehoch** [coop182/jquery.dfp.js#90]
In love with this library. It's let me do some awesome AJAX loading of ads for infinite scroll and slideshows on our site. Heck I even just recently launch lazy ads. All awesome.

But the problem is, jQuery DFP means I need to wait for jQuery to load... and the DOM to be ready. There's a noticeable 1 second or so delay before the ads load:

http://www.thehollywoodgossip.com

My idea was going to be hard-coding the two ATF the fold units we run (728x90 and 300x250 in sidebar) using old school GPT tags and then use jQuery DFP for all the fancy stuff we do BTF.

Has anyone successfully done this? Any advice on how to do so? Can they be combined?

**Comment by coop182** [comment]
Have you tried to run them both together yet? It should technically be possible... might just need to tweak things a bit... let me know what happens when you try to use both methods together... and if it is not working I can take a look at it... perhaps setup a test page :smile:

**Comment by ehoch** [comment]
I can confirm they do work:

http://origin.staging.thehollywoodgossip.com/

But it seems to blow up when I turn on Google Page Speed Service: 

http://staging.thehollywoodgossip.com/

Looks like I unfortunately have to ditch that unless you have any ideas..

**Comment by coop182** [comment]
I'm going to close this now as its a little outside the scope of this library... if you need help with this issue still please feel free to reopen it... :smile:

**Comment by ehoch** [comment]
And it definitely works with them both together. I currently do inline the ATF units and use your script for lazy loading BTF units. It's fantastic.
