### ISSUE TITLE
Data anonymization of Url Targeting

### ISSUE THREAD

**Issue by JohannesEH** [coop182/jquery.dfp.js#91]
We currently have a discussion with the folks at Google about anonymization of user-identifiable data in our targeting parameters such as emails, usernames, user ids etc. Supplying these kinds of targeting parameters is against the DFP terms of use, and can/will result in termination of your network if not handled properly.

At my current workplace we manage a semi-large network with multiple partner sites and we would like to see a generic solution to this problem implemented in jquery.dfp.js. So I'm starting this issue.

I propose a solution where we could pass a function (that takes the url string and returns an anonymized url string), in the jquery.dfp options such as:

    $('selector').dfp({
      dfpID: 'xxxxxxxxx',
      urlTargetingAnonymizer: function(url) {
        // do something to the url
        return url;
      }
    });

This function could then be used by the getUrlTargeting function if defined. It might even be helpful if jquery.dfp contained a generic implementation that looked for obvious things in the url such as email addresses and replaced them with dummy values.

However, we really need let people implement their own customized url anonymizes. Some examples where it would be necessary would be urls with the user id embedded in. For example a profile page with the path '/profile/53189/emailsettings' (The number '53189' being a unique user id) should be anonymized to something like 'profile/userid/emailsettings'.

I welcome any suggestions or discussion about this topic. I'll probably be making a pull request later today with a first draft implementation of the proposed solution.

**Comment by willhaynes** [comment]
What is the benefit of providing a function? Couldn't the URL to set for targeting just be passed directly in to "override" the default URL?

ex:

```
$('selector').dfp({
  dfpID: 'xxxxxxxxx',
  url: 'http://anonurl.com/user-xxx/emailsettings'
  }
});
```

You could still provide a call to a function in order to generate this for you.

**Comment by JohannesEH** [comment]
Yeah that would work, and is much simpler/better than my proposal.

I'm just realizing that since the urlTargeting information is taken not just from window.location but also  window.location.pathname & window.location.host, so we would have to parse the url "manually". I found [this GIST](https://gist.github.com/jlong/2428561) which utilizes the "a" DOM element to parse the an url. I'm not sure if there are any downsides to doing it that way.

**Comment by JohannesEH** [comment]
It seems as though the "a" element dom parser way is relatively slow. We could use a RFC compliant regex to parse the url instead, which would be faster, but also way bigger as well as more difficult to test and maintain.

See [this page](http://jmrware.com/articles/2009/uri_regexp/URI_regex.html) for details on a RFC compatible regex implementation.

**Comment by coop182** [comment]
Thanks for this... I think its a good idea... adds the ability for people to follow the T&C's if they want to :smile:

**Comment by JohannesEH** [comment]
@coop182 yeah it's probably not something all users need, but when you do, it's nice to have the functionality there. I'm a little bit worried about the new url parsing might not have been 100% backwards compatible with the way window.location was being used. I'll try and test it today and patch the code if it is necessary and possible.

**Comment by coop182** [comment]
Ok I just gave it a test and yes it was not quite right for the targeting domain, have fixed that now and put a test in to make sure that the right data is being returned.

**Comment by JohannesEH** [comment]
@coop182 thanks!
