### ISSUE TITLE
"inURL" url targeting no longer needed?

### ISSUE THREAD

**Issue by JohannesEH** [coop182/jquery.dfp.js#92]
DFP now supports "contains" and "begins with" operators in custom criteria targeting. Does this remove the need for the 'inURL' targeting option in jquery.dfp?

![dfp targeting](https://cloud.githubusercontent.com/assets/118692/6811368/74ae1340-d267-11e4-94e1-2fa5674ee652.png)

**Comment by coop182** [comment]
Looks like you might be right... I will take a closer look when I get a bit more time and see if this can be tidied up without losing any functionality. :smile:

**Comment by JohannesEH** [comment]
@coop182 I couldn't find any reference to this functionality in the DFP docs, so I'll be doing some testing today and post my findingsin this thread. Furthermore this would definitely be a breaking change jquery.dfp so it might mean the version have to be bumped to 2.0.0?

**Comment by coop182** [comment]
Yeah it would definitely be a major version bump... I probably wont get time to look at this until the weekend at this stage.

**Comment by JohannesEH** [comment]
@coop182 I will implement the change (remove the inURL functionality), test it and send a pull request. later today (I'm in UTC+1). Then you can merge it or use it as a base when you.

Btw, I'm thinking that there might be some other breaking changes and cleanup tasks (like naming changes etc.) that would be nice to do at the same time if you're going to do a major version bump. I have a few suggestions. Maybe we could start a new version 2.0.0 issue and discuss it there.
