### ISSUE TITLE
Missing possibility to set correlator

### ISSUE THREAD

**Issue by mikkotikkanen** [coop182/jquery.dfp.js#97]
googletag takes two arguments, first being the slot array and another options. Options enables you to pass on correlator setting, which is required for single page apps to refresh ads correctly.

Like so:
```js
googletag.pubads().refresh(null, {changeCorrelator: false});
```

**Comment by coop182** [comment]
You could just call the refresh function outside of my script?

```javascript
window.googletag.pubads().refresh(null, {changeCorrelator: false});
```

You just have to make sure the ad units have been initialised.
