### ISSUE TITLE
Missing possiblity to update settings after initialization without refreshing

### ISSUE THREAD

**Issue by mikkotikkanen** [coop182/jquery.dfp.js#98]
When you have cases like loading targeting data from other sources, you need to delay the actual loading of the ads until you have the data (this is why `disableInitialLoad` is there). Meanwhile, slots can be initialized (aka. iframes created).

However, now I can't just update targeting data separately, after the fact, and then call refresh when I'm done.

**Comment by coop182** [comment]
You should also be able to do this by calling DFP directly outside of this script.

```javascript
window.googletag.pubads().setTargeting('key', 'value');
window.googletag.pubads().refresh();
```

You might need a callback from my script to let you know when the ad slots have been initialised?
